### ISSUE TITLE
stopped streaming

### ISSUE THREAD

**Issue by formatme** [sstativa/mfc-node#8]
i just keep getting stopped streaming after it says starting capturing process

**Comment by sstativa** [comment]
First of all you should enable `debug` mode in config file to get more ideas about you problem. However my first guess will be you have a problem with ffmpeg.exe file (if you on Windows). Just check that you can launch ffmpeg from command line.

**Comment by Toxicsp** [comment]
Same problem here. And ffmpeg working OK.

**Comment by sstativa** [comment]
The only way it could happen if ffmpeg can't start either because passed params are wrong or there is an issue with local filesystem (ex. path does not exist).

```
      var spawnArguments = [
        '-hide_banner',
        '-v',
        'fatal',
        '-i',
        'http://video' + (model.camserv - 500) + '.myfreecams.com:1935/NxServer/ngrp:mfc_' + (100000000 + model.uid) + '.f4v_mobile/playlist.m3u8?nc=1423603882490',
        // 'http://video' + (model.camserv - 500) + '.myfreecams.com:1935/NxServer/mfc_' + (100000000 + model.uid) + '.f4v_aac/playlist.m3u8?nc=1423603882490',
        '-c',
        'copy',
        config.captureDirectory + '/' + filename
      ];
```
Try to comment `-v` and `fatal` lines, like: 
```
   // '-v',
   // 'fatal',
```
And start `main.js` again. This time there will be some additional output to identify the problem.

**Comment by Toxicsp** [comment]
Solved, it was a full disk problem. Thanks!
